ITEM.name = "Sparkling Water"
ITEM.desc = "A blue can of plain water."
ITEM.model = "models/props_junk/popcan01a.mdl"
ITEM.category = "Еда"
ITEM.skin = 2
ITEM.hunger = 0
ITEM.thirst = 20
ITEM.empty = false
ITEM.permit = "food"