ITEM.name = "Мусор"
ITEM.desc = "Пустая Алюминивая Банка."
ITEM.model = "models/props_junk/popcan01a.mdl"
ITEM.category = "Еда"
ITEM.skin = 2
ITEM.hunger = 0
ITEM.thirst = 0
ITEM.empty = true
ITEM.permit = "food"